package container

const (
	WEAVE_CIDR       = "WEAVE_CIDR"
	DEFAULT_PORT     = 80
	SERVICE_PORT     = "SERVER_PORT"
	SERVICE_NAME     = "SERVICE_NAME"
	HEALTH_CHECK_URL = "HEALTH_CHECK_URL"
	SERVICE_SOURCE   = "SERVICE_SOURCE"
)
